/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MoodboardRouteImport } from './routes/moodboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MoodboardPresentRouteImport } from './routes/moodboard.present'

const MoodboardRoute = MoodboardRouteImport.update({
  id: '/moodboard',
  path: '/moodboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MoodboardPresentRoute = MoodboardPresentRouteImport.update({
  id: '/present',
  path: '/present',
  getParentRoute: () => MoodboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/moodboard': typeof MoodboardRouteWithChildren
  '/moodboard/present': typeof MoodboardPresentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/moodboard': typeof MoodboardRouteWithChildren
  '/moodboard/present': typeof MoodboardPresentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/moodboard': typeof MoodboardRouteWithChildren
  '/moodboard/present': typeof MoodboardPresentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/moodboard' | '/moodboard/present'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/moodboard' | '/moodboard/present'
  id: '__root__' | '/' | '/moodboard' | '/moodboard/present'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MoodboardRoute: typeof MoodboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/moodboard': {
      id: '/moodboard'
      path: '/moodboard'
      fullPath: '/moodboard'
      preLoaderRoute: typeof MoodboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moodboard/present': {
      id: '/moodboard/present'
      path: '/present'
      fullPath: '/moodboard/present'
      preLoaderRoute: typeof MoodboardPresentRouteImport
      parentRoute: typeof MoodboardRoute
    }
  }
}

interface MoodboardRouteChildren {
  MoodboardPresentRoute: typeof MoodboardPresentRoute
}

const MoodboardRouteChildren: MoodboardRouteChildren = {
  MoodboardPresentRoute: MoodboardPresentRoute,
}

const MoodboardRouteWithChildren = MoodboardRoute._addFileChildren(
  MoodboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MoodboardRoute: MoodboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
