/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PresentRouteImport } from './routes/present'
import { Route as MoodboardRouteImport } from './routes/moodboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as AdminImportRouteImport } from './routes/admin.import'
import { Route as AdminCatalogRouteImport } from './routes/admin.catalog'

const PresentRoute = PresentRouteImport.update({
  id: '/present',
  path: '/present',
  getParentRoute: () => rootRouteImport,
} as any)
const MoodboardRoute = MoodboardRouteImport.update({
  id: '/moodboard',
  path: '/moodboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminImportRoute = AdminImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCatalogRoute = AdminCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/moodboard': typeof MoodboardRoute
  '/present': typeof PresentRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/moodboard': typeof MoodboardRoute
  '/present': typeof PresentRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/moodboard': typeof MoodboardRoute
  '/present': typeof PresentRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/moodboard'
    | '/present'
    | '/admin/catalog'
    | '/admin/import'
    | '/admin/leads'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/moodboard'
    | '/present'
    | '/admin/catalog'
    | '/admin/import'
    | '/admin/leads'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/moodboard'
    | '/present'
    | '/admin/catalog'
    | '/admin/import'
    | '/admin/leads'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  MoodboardRoute: typeof MoodboardRoute
  PresentRoute: typeof PresentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/present': {
      id: '/present'
      path: '/present'
      fullPath: '/present'
      preLoaderRoute: typeof PresentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moodboard': {
      id: '/moodboard'
      path: '/moodboard'
      fullPath: '/moodboard'
      preLoaderRoute: typeof MoodboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/import': {
      id: '/admin/import'
      path: '/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AdminImportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/catalog': {
      id: '/admin/catalog'
      path: '/catalog'
      fullPath: '/admin/catalog'
      preLoaderRoute: typeof AdminCatalogRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCatalogRoute: typeof AdminCatalogRoute
  AdminImportRoute: typeof AdminImportRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCatalogRoute: AdminCatalogRoute,
  AdminImportRoute: AdminImportRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  MoodboardRoute: MoodboardRoute,
  PresentRoute: PresentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
